scopes:
    posts:
        label: Selecciones el o los posts del blog que desea ver sus comentarios
        modelClass: Rainlab\Blog\Models\Post
        conditions: post_id in (:filtered)
        nameFrom: title
