# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Comment

# Model Form Field configuration
form: $/cmantikweb/simplecomments/models/comments/fields.yaml

# Model Class name
modelClass: Cmantikweb\Simplecomments\Models\Comments

# Default redirect location
defaultRedirect: cmantikweb/simplecomments/comments

# Create page
create:
    title: Create Comment
    redirect: cmantikweb/simplecomments/comments/update/:id
    redirectClose: cmantikweb/simplecomments/comments

# Update page
update:
    title: Edit Comment
    redirect: cmantikweb/simplecomments/comments
    redirectClose: cmantikweb/simplecomments/comments

# Preview page
preview:
    title: Preview Comment
