scopes:
    posts:
        label: select the blog post (s) you want to see your comments
        modelClass: Rainlab\Blog\Models\Post
        conditions: post_id in (:filtered)
        nameFrom: title
